version: '3.8'

services:
  latex:
    image: latexcompiler
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./GroupTemplate
        target: /groupreport
